# Generated by Django 4.1.5 on 2023-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='')),
                ('lastname', models.CharField(max_length=50, verbose_name='')),
                ('age', models.CharField(max_length=50, verbose_name='')),
                ('email', models.CharField(max_length=50, verbose_name='')),
                ('pno', models.CharField(max_length=50, verbose_name='')),
                ('gender', models.CharField(max_length=50, verbose_name='')),
                ('isftd', models.CharField(max_length=50, verbose_name='')),
                ('bloodgroup', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('pincode', models.CharField(max_length=50, verbose_name='')),
                ('state', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='')),
                ('lastname', models.CharField(max_length=50, verbose_name='')),
                ('age', models.CharField(max_length=50, verbose_name='')),
                ('email', models.CharField(max_length=50, verbose_name='')),
                ('pno', models.CharField(max_length=50, verbose_name='')),
                ('gender', models.CharField(max_length=50, verbose_name='')),
                ('bloodgroup', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('pincode', models.CharField(max_length=50, verbose_name='')),
                ('state', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
